# Generated by Django 5.2.7 on 2025-10-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_alter_employee_table'),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.TextField()),
                ('has_media', models.BooleanField(default=False)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('system_creation_time', models.DateTimeField(auto_now_add=True)),
                ('system_update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project.project')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='employee.employee')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
