# Generated by Django 5.2.7 on 2025-10-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('system_creation_time', models.DateTimeField(auto_now_add=True)),
                ('system_update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active'), ('5', 'Deleted')], default='1', max_length=1)),
            ],
        ),
    ]
