# Generated by Django 5.2.7 on 2025-10-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('banner_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('system_creation_time', models.DateTimeField(auto_now_add=True)),
                ('system_update_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='employee.employee')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
